var arr1 = [
	{
		"name":"蟹老板",
		"position":"班级导师",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-01.jpeg"
	},
	{
		"name":"关帅",
		"position":"班级导师",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"黄指导",
		"position":"班级导师",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"付总",
		"position":"班级导师",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-04.jpeg"
	},
	{
		"name":"龙老师",
		"position":"班级导师",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-03.jpeg"
	},
	{
		"name":"李老板",
		"position":"班级导师",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	}
]
var arr2 = [
	{
		"name":"梁晓枫",
		"position":"班委-班长",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-01.jpeg"
	},
	{
		"name":"卢天由",
		"position":"班委-副班",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"杨新宇",
		"position":"班委-团支书",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"姚秀乔",
		"position":"班委-学委",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-04.jpeg"
	},
	{
		"name":"黄创明",
		"position":"班委-学委",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-01.jpeg"
	},
	{
		"name":"钟安纯",
		"position":"班委-文体委",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-02.jpeg"
	},
	{
		"name":"石梦琼",
		"position":"班委-组织委",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-03.jpeg"
	},
	{
		"name":"徐业妙",
		"position":"班委-生劳委",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-04.jpeg"
	},
	{
		"name":"劳海基",
		"position":"班委-纪检委",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"谭欲昌",
		"position":"班委-宣传委",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	}
]
var arr3 = [
	{
		"name":"蒋越",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-01.jpeg"
	},
	{
		"name":"周严",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"郑美燕",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-03.jpeg"
	},
	
	{
		"name":"杨新宇",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-04.jpeg"
	},
	{
		"name":"蒙丽燕",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-03.jpeg"
	},
	
	{
		"name":"朱起圆",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-02.jpeg"
	},
	{
		"name":"徐业妙",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-01.jpeg"
	},
	
	{
		"name":"谭裕昌",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"李 鑫",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"马彩亮",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-04.jpeg"
	},
	{
		"name":"陈政楠",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	
	{
		"name":"钟安纯",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-02.jpeg"
	},
	{
		"name":"蒙予磊",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-01.jpeg"
	},
	{
		"name":"陆厚良",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"吴珠珠",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-03.jpeg"
	},
	{
		"name":"卢天由",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-04.jpeg"
	},
	{
		"name":"罗艳宁",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"劳海基",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"莫家铭",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-01.jpeg"
	},
	{
		"name":"何立清",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"饶海勇",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"黄创明",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-04.jpeg"
	},
	{
		"name":"庞玉广",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"潘新华",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"韦海钊",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-01.jpeg"
	},
	{
		"name":"周小龙",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"黄子健",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"梁晓枫",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-04.jpeg"
	},
	{
		"name":"蒋 雄",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"李晓婷",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-04.jpeg"
	},
	{
		"name":"梁鸿文",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-03.jpeg"
	},
	{
		"name":"姚秀乔",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nan-02.jpeg"
	},
	{
		"name":"周 妮",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-01.jpeg"
	},
	{
		"name":"陈 琳",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-02.jpeg"
	},
	{
		"name":"劳雪勤",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-03.jpeg"
	},
	{
		"name":"石梦琼",
		"position":"班级成员",
		"manifesto":"111",
		"src":"../img/chengyuan/cy-bjcy-nv-04.jpeg"
	},
	
	
]
var vm = new Vue({
	el:"#cy-lieb",
	data:{
		sites: arr1,
		classCommittees: arr2,
		members: arr3,
	}
	
})